module.exports = {
  WX_HEADER_CODE: 'code',
  WX_HEADER_ENCRYPTED_DATA: 'encryptedData',
  WX_HEADER_IV: 'iv',
  WX_HEADER_TOKEN: 'token',
  WX_HEADER_REGISTER: 'isRegister',
  WX_HEADER_RAWDATA: 'rawData',

  WX_SESSION_MAGIC_ID: 'token',

  CODE_USER_TOKEN_FAIL: '99999',

  ERR_INVALID_PARAMS: 'ERR_INVALID_PARAMS',

  ERR_WX_LOGIN_FAILED: 'ERR_WX_LOGIN_FAILED',
  ERR_WX_GET_USER_INFO: 'ERR_WX_GET_USER_INFO',
  ERR_LOGIN_TIMEOUT: 'ERR_LOGIN_TIMEOUT',
  ERR_LOGIN_FAILED: 'ERR_LOGIN_FAILED',
  ERR_LOGIN_SESSION_NOT_RECEIVED: 'ERR_LOGIN_MISSING_SESSION',

  ERR_INVALID_SESSION: 'ERR_INVALID_SESSION',
  ERR_CHECK_LOGIN_FAILED: 'ERR_CHECK_LOGIN_FAILED',
};